### ISSUE TITLE
Can we add GitHub Action to auto push to nuget?

### ISSUE THREAD

**Issue by lindexi** [AvaloniaUI/avalonia-dotnet-templates#33]
And I can not find the template from nuget.org

**Comment by Takoooooo** [comment]
How can it be useful? I usually test everything before publishing and also we have a thing on Azure pipelines that push an artefact to NuGet

**Comment by ForNeVeR** [comment]
Since you have defined the process (with manual testing), set up the automation (on Azure and not GitHub, doesn't matter much), and got the templates on nuget.org, then I believe all the purposes of this issue have been fulfilled, and it can be closed.

At least, as an issue voter (and an Avalonia template user) I would vote for this.
